### ISSUE TITLE
Comparable Rust sample

### ISSUE THREAD

**Issue by DazWilkin** [grpc-ecosystem/grpc-cloud-run-example#13]
I've added a Rust sample to my fork.

I'm a Rust noob so there's likely plenty of feedback but:

+ It works
+ It's straightforward
+ Google should show more Rust <3 :-)

I'm always confused by GitHub when PR'ing from different branches because, even though I started each sample from its own branch, the PRs show all my commits :-(

**Comment by gnossen** [comment]
Great! I've never actually looked at the Rust bindings before, but it would be amazing to get a Rust version in this repo!

**Comment by gnossen** [comment]
Resolved by #15.
