### ISSUE TITLE
Node example works locally but not when deployed to Cloud Run

### ISSUE THREAD

**Issue by mikaelvesavuori** [grpc-ecosystem/grpc-cloud-run-example#23]
Hi, and thanks for the multiple, concise examples!

As the title says, using the Node example locally works fine. However, I am having issues using `grpcurl` towards the Cloud Run URL. When doing so I get the error:

```
Failed to process proto source files.: could not parse given files: %!v(PANIC=Error method: runtime error: invalid memory address or nil pointer dereference)
```

I'm not unused to Docker but am not an expert either. Totally new to gRPC. My highly naive suspicions relate to:
a) Do proto files exist on the image? (Which I absolutely believe they do, since the local one works)
b) Some kind of error in the proto files? Do they need to be (re)built?

Thanks for any assistance.

**Comment by gnossen** [comment]
This looks like some sort of internal error in `grpcurl`. A couple of questions to help guide troubleshooting here:
 - How did you get `grpcurl`? Did you download a binary? Which version? Did you compile from source?
 - From which directory are you running this command? The READMEs assume that you're running `grpcurl` from your host machine, not in a docker container, but your comment implies that you're running from within a container. That should work in principle, but you might run into issues like libc incompatibility for certain flavors of image.

**Comment by mikaelvesavuori** [comment]
Hi again.

I fully accept this may be an issue with `grpcurl` rather than with this repo. I got `grpcurl` by running the one-liner in the README, by the way. It's not running in a container, it's all run from my own machine or from the Cloud Shell, outside of Docker.

My previous attempt(s) used a copy of the repo with only the Node folder, and also setting `const PORT = process.env.PORT || 8080` just in case... Just now I also tried running it with the `deploy.sh` in the root but with the exact same result.

Going to the Cloud Run URL returns "Service Unavailable". I suppose that's expected this being gRPC?

Weird.

**Comment by gnossen** [comment]
You've probably got the `1.6` release then. Can you try the [1.5 release](https://github.com/fullstorydev/grpcurl/releases/tag/v1.5.0) and see if that resolves the issue?

**Comment by mikaelvesavuori** [comment]
Still same error, unfortunately...

```
  mikaelvesavuori@mikaels-mbp  ~  grpcurl --version
grpcurl v1.5.0
 mikaelvesavuori@mikaels-mbp  ~  echo $ENDPOINT   
https://grpc-calculator-wxbfuxfzxa-lz.a.run.app
 mikaelvesavuori@mikaels-mbp  ~  grpcurl \        
    -proto protos/calculator.proto \
    -d '{"first_operand": 2.0, "second_operand": 3.0, "operation": "ADD"}' \
    ${ENDPOINT}:443 \
    Calculator.Calculate
Failed to process proto source files.: could not parse given files: open protos/calculator.proto: no such file or directory
 ✘ mikaelvesavuori@mikaels-mbp  ~   
```

**Comment by gnossen** [comment]
Drop the `https://`

**Comment by mikaelvesavuori** [comment]
Thanks. Will add a PR so any other newbs out there don't trip up on this! 😄
