### ISSUE TITLE
Does Cloud Run support grpc-web client requests?

### ISSUE THREAD

**Issue by silenceisgolden** [grpc-ecosystem/grpc-cloud-run-example#7]
Hey all, I figure this may be a decent spot to ask this question, but feel free to redirect it if necessary!

Does Cloud Run support grpc-web clients? I'm not sure about the status of the grpc-web project in general, but I would love to see or contribute an example in this repo if the support is there or is planned to be there.

Thanks!

**Comment by gnossen** [comment]
@silenceisgolden To my knowledge, Cloud Run does not support gRPC Web clients. It seems like an interesting use case though. Maybe @steren or @jasonpolites can comment further.

**Comment by steren** [comment]
Cloud Run supports unary gRPC, so I would expect it to support unary gRPC web. Please give it a try and let us know.

**Comment by wlhee** [comment]
gRPC-web project is GA. 

Cloud Run currently doesn't natively support gRPC-web. But user can include a proxy in the container to do gRPC-web to gRPC transcoding, see:
https://blog.envoyproxy.io/envoy-and-grpc-web-a-fresh-new-alternative-to-rest-6504ce7eb880

**Comment by silenceisgolden** [comment]
Not quite _the_ solution, but this is super interesting as an interim solution https://cloud.google.com/endpoints/docs/openapi/get-started-cloud-run

**Comment by gnossen** [comment]
Going ahead and closing since I believe the question has been answered.
