### ISSUE TITLE
running example on Mac OS X Catalina

### ISSUE THREAD

**Issue by Pega88** [grpc-ecosystem/grpc-cloud-run-example#8]
had to change my grpcurl request paramter order to this to make it work:

```bash
grpcurl \
	-d '{"first_operand": 2.0, "second_operand": 3.0, "operation": "ADD"}' \
	-proto calculator.proto \
	--plaintext \
    localhost:50051 \
    Calculator.Calculate
```

otherwise I get
```
Too many arguments.
Try 'grpcurl -help' for more details.
```

**Comment by DazWilkin** [comment]
Could it be that the flag should be `-plaintext` rather than `--plaintext`?

**Comment by gnossen** [comment]
@Pega88 Thanks for the report! https://github.com/grpc-ecosystem/grpc-cloud-run-example/pull/10 addresses this!
